name: BN10 Scraper

on:
  # Run manually
  workflow_dispatch:

jobs:
  scrape:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y tesseract-ocr

      - name: Install Python dependencies
        run: |
          python -m pip install --upgrade pip
          pip install .

      - name: Run scraper
        run: |
          python3 src/main.py

      - name: Upload results
        uses: actions/upload-artifact@v4
        with:
          name: scraper-results
          path: src/output.db
          retention-days: 30
